Add controllers
ARGalimov/java-shareit pull request #1
Opened 2023-07-24 17:59 UTC by ARGalimov

2023-07-25 18:06 UTC, Yang-Pi requested changes

2023-07-25 18:06 UTC, Yang-Pi commented on pom.xml
> +    <dependencies>
В качестве улучшения: зависимостей становится больше, их нужно поддерживать, те нужно искать какую-нибудь, поэтому их лучше группировать - либо по задачам (сервер, бд и тп), либо по названиям (все спринговые, потом для бд, потом для джавы типо ломбока)

2023-07-25 18:06 UTC, Yang-Pi commented on pom.xml
А подскажи, где ты взял основу для pom файла - вам предоставил наставник или сам нашел?

2023-07-25 18:06 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/Item.java
> +        if (Objects.isNull(name) || Objects.isNull(description) || name.isEmpty() || description.isEmpty()) {
Ты уже реализовал подобную валидацию аннотациями, поэтому это условие излишне

2023-07-25 18:06 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        id++;
А давай сделаем, как в 3м спринте для менеджера задач - метод вроде generateId() который бы возвращал значение и инкерментировал поле id, потому что сейчас нужно не забыть написать id++, можно чисто случайно забыть и появятся дубликаты

2023-07-25 18:06 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapperImpl.java
> +        Item item = itemStorage.find(id);
Проверь, что что-то нашлось

2023-07-25 18:06 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto update(@RequestBody UserDto userDto, @PathVariable Integer id) {
Тоже используй аннотацию Valid, чтобы проверить, что запрос на обновление верный

2023-07-25 18:06 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @PatchMapping(value = "/{id}")
Ты используешь тип запроса PATCH, но логика сервиса реализована как для PUT, что потенциально может привести к ошибкам в данным.
https://www.baeldung.com/cs/http-put-vs-patch#put-method:~:text=are%20idempotent%20methods-,3.%20PUT%20Method,-Clients%20use%20the

Комментарий актуален и для Item

2023-07-25 18:06 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/user/dto/UserMapperImpl.java
> +        User user = userStorage.find(id).orElseThrow(() -> {
В качестве доп задания можешь попробовать реализовать этот метод одним стримом, с использованием filter, map

2023-07-26 04:50 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapperImpl.java
> +        Item item = itemStorage.find(id);
Заменил на Optional и orElseThrow

2023-07-26 06:32 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/user/dto/UserMapperImpl.java
> +        User user = userStorage.find(id).orElseThrow(() -> {
попробовал, получилось.

2023-07-26 06:51 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto update(@RequestBody UserDto userDto, @PathVariable Integer id) {
поправил

2023-07-26 07:18 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +        id++;
Добавил

2023-07-26 07:20 UTC, ARGalimov commented on pom.xml
основа была изначально в проекте в ветке MAIN. Но при сборке в POM высветились 10 хайлайтов. Чтобы их убрать я игрался с зависимостями. Потом уже наставник подсказал как исправить в настройках Idea

2023-07-26 07:55 UTC, ARGalimov commented on pom.xml
> +    <dependencies>
пересортировал и подписал блоки

2023-07-26 11:40 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/item/Item.java
> +        if (Objects.isNull(name) || Objects.isNull(description) || name.isEmpty() || description.isEmpty()) {
поправил

2023-07-26 11:41 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @PatchMapping(value = "/{id}")
обновление только переданных полей реализовано на уровень ниже - в маппере

2023-07-26 17:35 UTC, Yang-Pi approved these changes

2023-07-26 17:35 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapperImpl.java
> +                .map(existingItem -> {
Блин, со стримом выглядит как-то хуже)) лучше вернуть императивный подход через if

2023-07-26 17:35 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/user/dto/UserMapperImpl.java
> +                .map(existingUser -> new User(existingUser.getId(),
Вот сделай также для ItemMapperImpl

2023-07-27 04:40 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/user/dto/UserMapperImpl.java
> +                .map(existingUser -> new User(existingUser.getId(),
Сделал

2023-07-27 04:40 UTC, ARGalimov commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapperImpl.java
> +                .map(existingItem -> {
Переделал аналогично UserMapperImpl

2023-07-27 04:40 UTC, merged